language: java

addons:
  sonarcloud:
    organization: "pitchounvivi"
#    Les 2 lignes suivantes ne sont pas nécessaire car le token a été mis directement dans Travis
#    token:
#      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=pitchounvivi_ipi-java-350-ex