language: java

addons:
  sonarcloud:
    organization: "matrak63"
    apt:
      update: true
      sources:
        - sourceline: "deb https://dl.bintray.com/gauge/gauge-deb stable main"
          key_url: "http://ha.pool.sks-keyservers.net/pks/lookup?search=0x023EDB0B&op=get&options=mr"
      packages:
        - gauge

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=matrak63_ipi-java-350-ex

