language: java

addons:
  sonarcloud:
    organization: "raaaahman-github" # the key of the org you chose at step #3
    token:
      secure: "OLzHg/xBNRg52PTTXVYabuDSvTO1ZakJ3nV13pw9uJTYji6uIILujnzpuKP59avynOnarZSsApcNH8yW33DFDIzzuJN42PbHMoBNL6sftIl1JFbo7gdft+ZegmpIgDcpLfxIrggysM165Dl/teI742kMUd889fuonY5dGVrm422bFpT6SwFzn0svl3h7MBsZQmGbo/KFioC0KFwB7oWmTTouDG400w8LY6r3CysHce75E0/aJYb66Yy6B/rC5AC3SSCIDSVUfwPUH+v9UtGWvHbb61PicCHTJvnf+3giUhXTsFdzsRscKWBCeARJ52rScNKrQA44EQUWW8e8pGeX/JAYnPvGwwWugxX1huXsx0q/Cub44XMuGniaaY/JqOw7NrIygyaHPXGU9sWm74HhwFE5KbC7u8RoSISEyVNbWIt0AX3kO0w8lyRuJfMSudABdbdcsGpTDm7UA3+vsqftM25REbYBjvFDaK003abX9oCzvtwSekrY20QA0ln4jRsBqbm7IIUolUWAiX2+E1SAxB/Kf+2xyz0miuBETeTRHaMFpRsMtsyz8wotmMlHhzRkCuttBSmSf2P+Xrkbpvjp97Erf7Rgk9qoc8bYiHBrO0QrhgK2Of633/wdOE3ZE6XfdlsFwZNjTyWdzRUvumVafvGPPxY+UjvFr81mhLEljcg="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=raaaahman_ipi-java-350-ex
