language: java

addons:
  sonarcloud:
    organization: "pjvilloud-github"

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=pjvilloud_ipi-java-350-ex
